version: "3.8"
services:
  server:
    build:
      dockerfile: dev.dockerfile
      context: ./backend
    restart: always
    ports:
      - 8080:8080
      - 4983:4983
    expose:
      - 8080
    volumes:
      - ./server/src:/app/src
      - ./server/nodemon.json:/app/nodemon.json
    links:
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8080
volumes:
  db-data: {}